#!/bin/bash
#Kevin Fan (26/4/17)
#Description: This script creates a local file named "CustomerDetails".
#Parameters are taken in from the user and stored/updates the CustomerDetails 
#file with customer details taken from the user

#Clears the screen content
clear

#This function asks user for customer email. The valid email function is called
#after to check is whether email is valid
function readEmail
{
	printf "Please enter the customer email address: "
	read email
	validEmail
}

#This function validates whether email entered is valid or not.
#If email is not valid the readEmail function is called again to ask user to 
#re-enter email address
function validEmail
{
	validEmail=false
	while [[ $validEmail = false ]]; do
		if [[ $email != *@*.* ]]; then
			printf "\n\tNot a valid email. Must contain @ and a .\n"
			readEmail
		elif [[ $(grep -i -c $email CustomerDetails) -ne 0 ]]; then
			printf "\n\tEmail already used\n"
			readEmail
		else
			validEmail=valid
		fi
	done
}


#This function asks user for phone number. The validPhoneNumber 
#function is then called to check is phone number is integars only
function readPhoneNumber
{
	printf "\nPlease enter the customer telephone Number: "
	read phoneNumber
	validNumber
}

#This function checks does phone number contain positive integars only.
#If not, the readPhoneNumber function to called again to ask user to re-enter
#phone number 
function validNumber
{
	if ! [[ $phoneNumber =~ ^[0-9]+$ ]]; then
		printf "\n\tInvalid character detected, only positive integers are allowed. Please re-renter phone number\n"
		readPhoneNumber
	fi
}

# If CustomerDetails file does not exist, create it
if [ ! -f CustomerDetails ]; then
    touch CustomerDetails
fi

#Call readEmail function 
readEmail

#Asks user for name and take in as parameter - no error checking is done 
while [[ -z $name ]]; do
	printf "\nPlease enter the customer name: "
	read name
done

#Asks user for alias and take in as parameter - no error checking is done
while [[ -z $alias ]]; do
	printf "\nPlease enter the customer alias: "
	read alias
done

#Asks user for address and take in as parameter - no error checking is done
while [[ -z $address ]]; do
	printf "\nPlease enter the customer address: "
	read address
done

#Calls the readPhoneNumber function to ask user for number and take in as parameter 
readPhoneNumber

#Takes the entered parameters, converts them to lowercase and list them in a file called CustomerDetails
echo "${email,,}	${name,,}	${alias,,}	${address,,}	$phoneNumber" >> CustomerDetails

# Sort the customer details
sort -o CustomerDetails CustomerDetails
printf "\n\tCustomer successfully added.\n"