#!/bin/bash
#Kevin Fan (Date)
#Description: This script creates a local file named "CustomerDetails".
#Parameters are taken in from the user and stored/updates the CustomerDetails 
#file with customer details taken from the user

#Clears the screen content
clear

function readEmail
{
	printf "\tPlease enter the customer email address: "
	read email
	validEmail
}

#This function validates whether email entered is entered is valid or not
function validEmail
{
	validEmail=false
	while [[ $validEmail = false ]]; do
		if [[ $email != *@*.* ]]; then
			printf "\n\tNot a valid email. Must contain @ and a .\n"
			readEmail
		elif [[ $(grep -i $email ../CustomerDetails | wc -l) -ne 0 ]]; then
			printf "\n\tEmail already used\n"
			readEmail
		else
			validEmail=valid
		fi
	done
	# uniqueEmail
}

# function uniqueEmail
# {
# 	uniqueEmail=$(grep $email ../CustomerDetails | wc -l)
# 	if [[  $uniqueEmail -ne 0 ]]; then
# 		printf "\t\nEmail already used\n"
# 		readEmail
# 	else
# 		readName
# 	fi
# }


#Asks user to enter email address. Need to error checking that email if unique
#and take emails contains @ with a . 

readEmail

printf "\n\tPlease enter the customer name: "
read name

printf "\n\tPlease enter the customer alias: "
read alias

printf "\n\tPlease enter the customer address: "
read address

printf "\n\tPlease enter the customer telephone Number: "
read phoneNumber

#Takes the entered parameters and list them in a file called CustomerDetails
echo "$email		$name		$alias		$address		$phoneNumber" >> ../CustomerDetails
printf "\n\tCustomer successfully added.\n\tPlease enter to return to main menu"
read