#!/bin/bash
#Kevin Fan (Date)
#Description: This script allows the user to search for an existing customer based upon
# any of the customers personal information

#Clear the console
clear

#Function that ask for user for search term and and then call the checkInput option 
function readInput
{
	#Asks user for search term
	printf "Please enter search term: "

	#Takes in serch term as parameter
	read input
	checkInput
}

#Function that checks the search term input and displays relevant options
#If no input is detected, the readInput function is called again for user to re-enter
#If matches are found, the mathces are displayed, and the actionAfterSearch is called
#If no matches are found, the actionAfterSearch is called
function checkInput
{
	if [ -z $input ]; then
		printf "\n\tNo entry detected. Please re-enter search term"
		readInput
	elif [[ $(grep -i $input CustomerDetails | wc -l) -ne 0 ]]; then
		printf "\n$(grep -i -c $input CustomerDetails) match(s) were found:\n"
		grep -i $input CustomerDetails 
		actionAfterSearch
	elif [[ $(grep -i $input CustomerDetails | wc -l) -eq 0 ]]; then
		printf "\nNo matches were found\n"
		actionAfterSearch
	fi
}

#Function that displays options for user after the first search
#Users can perform another search or return to main menu
#If an invalid option is entered, the script returns the the main menu
function actionAfterSearch
{
	validChoice=false
	while [[ $validChoice = false ]]; do
		printf "\n\t1) Perform another search\n"
		printf "\n\t=============================\n"
		printf "\n\t0) Return to Main Menu\n"
		printf "\nEnter choice: "
		read choice
			if ! [[ $choice =~ ^-?[0-9]+$ ]]; then
				printf "\nInvalid (String) entry, only integers shown are allowed. Please re-renter option\n"
			elif [ $choice -le -1 ] || [ $choice -ge 3 ]; then
				printf "\nInvalid number entered\n"
			elif [[ $choice -eq 1 ]]; then
				readInput
			else
				validChoice=valid
			fi
	done
}

#Calls the readInput function that begins the search loop. This loop is exited to main menu 
#is exited to main menu if an invalid option is entered or at revelvant options
readInput